[4단계 - 페이먼츠] 유세지(김용래) 미션 제출합니다. (moonheekim0118#1)
usageness/react-payments pull request #1
Opened 2022-06-19 12:26 UTC by usageness

@moonheekim0118
안녕하세요, **호프!**
이번 스터디의 첫 리뷰 요청을 드리게 된 유세지입니다 😊

`component/common` 디렉토리에 있던 컴포넌트들은
이전의 step3에서 타입스크립트로 마이그레이션을 진행했고,
오스틴에게 리뷰를 받았던 부분이라 이번엔 넘어가주셔도 좋습니다 🙌

제가 타입스크립트를 제대로 사용해 본 적이 없어 리뷰에 어려움을 겪으실 수도 있겠지만,
이미 스터디는 시작했으니...ㅋㅋ 저를 견뎌주세요. 😎

남은 방학 잘 보내시고 호프의 PR도 기다리겠습니다~

2022-06-19 16:06 UTC, moonheekim0118 requested changes
안녕하세요 세지! 리뷰를 맡은 호프입니다 😄 저도 타입스크립트가 매우매우 부족하지만 그래도 있는 지식 쥐어짜서 리뷰해보았어요. ㅋㅋㅋㅋ 진짜 제가 아는 모오오든 타입스크립트 지식을 쥐어짰습니다..ㅋㅋㅋㅋㅋ

일단 전체적인 리뷰는 아래와 같아요.

1. **Type 네이밍 컨벤션을 통일하면 좋겠어요!**
- 어떤 타입은 interface 이름이 소문자로 시작했다가, 또 다른 곳에서는 대문자로 시작하니까 통일성이 조금 떨어져서 아쉬워요.
- 어떤 타입은 뒤에 -*Type 포스트픽스를 붙여주고, 또 어떤타입은 안붙여주니까, 통일성이 조금 떨어져서 아쉬워요.
 

2. **Button Element 나 Input Element 와 같은 컴포넌트의 Props는 상속을 사용하는게 어떨까요?**
- 이 부분은 리뷰에 자세히 남겨놓았습니다!


3. **PropsWithChildren 사용해서 children 타이핑하기** 
```tsx

interface Props = {
  name: string
}

function Example(props: React.PropsWithChildren<Props>) {
  return <div>{props.children}</div>
}
```
- 이렇게하면 굳이 children 타입을 직접 정의해줄 필요 없답니다 :)

2022-06-19 16:06 UTC, moonheekim0118 commented on src/components/cardRegister/CardExpireDateInput.tsx
> +
문자열을 숫자로 타입 변환해주기 위해서 parseInt 를 사용한 것으로 보이는데,
제가 알기로 parseInt 로 숫자로 변환하는것과 Number 로 숫자를 변환하는것은 차이가 있는걸로 아는데요, 혹시 의도적으로 parseInt를 사용하신걸까용?

parseInt -> 문자열을 분석하는 과정이 포함됨, 두번째 인자로 들어간 진수를 사용해 정수로 변환
Number -> 문자열을 숫자로 변환

그래서 parseInt의 문제점은 크게 두가지 인걸로 알고 있어요!
1. 두번째 인자를 넣지 않고 사용하는 것은 위험함 => 특정 브라우저에서는 다르게 동작 할 여지가 있음
2. '문자열을 분석'하는 과정이 포함되어 성능상 불리

2022-06-19 16:06 UTC, moonheekim0118 commented on src/components/cardRegister/CardNumbersInput.tsx
> +
useRef 에 타입이 누락되었네요 🧐 제대로 타입 추론이 되고 있을까요 ? 의도하신걸까요~?

2022-06-19 16:06 UTC, moonheekim0118 commented on src/components/common/InputBasic.tsx
> +  maxLength?: string | number;
`type , placeholder, value, onChange, onBlur id, maxLength` 와 같은 속성들을 다 타입으로 정의해주고 있는데요..! 아래와 같이 엘리먼트 타입을 상속받아서 사용하면, html 에 내장된 네이티브 속성들은 따로 타입을 정의해주지 않아도 된답니다

 ```suggestion
interface InputBasicComponent extends React.InputHTMLAttributes<HTMLInputElement> {
  dataTestId?: string;
  pattern?: string;
  width?: string;
  inputRef?:
    | React.RefObject<HTMLInputElement>
    | ((element: HTMLInputElement) => HTMLInputElement);

```

2022-06-19 16:06 UTC, moonheekim0118 commented on src/components/common/InputUnderline.tsx
> +}
이것도 위에서 코멘트 드린대로 상속받으면 타이핑 할게 많이 줄어들겠죵..?!

2022-06-19 16:06 UTC, moonheekim0118 commented on src/components/common/Button.tsx
> +  textAlign?: textAlign;
여기도 마찬가지로 상속받으면 타이핑할게 줄어들겠어요!
```suggestion
interface ButtonComponent extends React.ButtonHTMLAttributes<HTMLButtonElement>{
  children?: React.ReactNode;
  disabled?: boolean;
  textAlign?: textAlign;
```

2022-06-19 16:06 UTC, moonheekim0118 commented on src/components/cardRegister/CardExpireDateInput.tsx
> +    }
저의 아주 개인적인 의견이지만,  
`parseInt(value)>12 `는 validation 의 영역이고,
`Number.isNaN(value)` 은 타입가드의 영역인 것 같은데, 나눠서 처리하는게 어떨까요?

그리고, value 가 string 타입인 것 같은데 이 경우 어떤 문자열을 넣어도 `Number.isNaN` 의 결과값이 false 로 나오지 않나용..?!

```suggestion

    const valueAsNumber = Number(value);
    
    if(Number.isNaN(valueAsNumber) return;
    if(valueAsNumber > 12) return;
   
```

2022-06-19 16:06 UTC, moonheekim0118 commented on src/components/common/PageTitle.tsx
> +  onClick?: () => void;
onClick 에 event 객체가 인자로 넘어올텐데! 혹시 의도적으로 누락하신건지, 아니면 깜빡하신건지! 궁금합니다 😙

2022-06-19 16:06 UTC, moonheekim0118 commented on src/constants/constants.ts
> +};
```suggestion
export const RULE_INPUT = {
  CARD_NUMBER_RULE: "[0-9]{4}",
  EXPIRE_DATE_RULE: "[0-9]{2}",
  CVC_RULE: "[0-9]{3}",
  PASSWORD_RULE: "[0-9]{1}",
} as const ;
```

상수 객체에 as const 가 추가되면 readonly 가 되어서 더 안전하지 않을까요? ㅎㅎ

2022-06-19 16:06 UTC, moonheekim0118 commented on src/pages/CardRegisterPage.tsx
> +  });
헉 타입스크립트 이 똑똑한 녀석..! 객체도 타입추론 따박따박 잘해주네요!!?!

2022-06-19 16:06 UTC, moonheekim0118 commented on src/pages/CardRegisterPage.tsx
> +  };
return 문이 있으니까, return type 도 정의해주는것 어떨까요 ?

2022-06-19 16:06 UTC, moonheekim0118 commented on src/utils/currentDate.js
> +};
![](https://thumbs.gfycat.com/BronzeThreadbareGavial-max-1mb.gif)
어라라 자스 너 오랜만이다~~

2022-06-19 16:06 UTC, moonheekim0118 commented on src/types/card.interface.ts
> +  cardCVC: string;
id 가 string | number 라.. 🧐 .. 
타입을 두개로 받기보다는,  일찌감치 타입을 하나로 통일해서 받는게 좋지 않을까요?!

2022-06-19 16:06 UTC, moonheekim0118 commented on src/types/css.type.ts
> +};
css 관련 타입을 다 정의해주셨네요 👍 👍 꼼꼼!

그런데..! 이를 뭔가 리액트에서 제공해줄 것만 같은 느낌적인 느낌..?!
찾아보니 React.CSSProperties 라는 타입을 리액트에서 제공해주네요..?!
저도 잘모르겠으니 같이 공부해보아요.
https://use-form.netlify.app/interfaces/_node_modules__types_react_index_d_.react.cssproperties.html

https://fettblog.eu/typescript-react/styles/

2022-06-19 16:24 UTC, moonheekim0118 commented on src/types/card.interface.ts
> +}
이거 타입핑이 반복되는데 Record 어때요..? (나도 잘 모름, 잘 안써봤음. 그냥 Record 간지나고 더 안전하대서 제안함)

```suggestion

type CardNumbers = Record<'firstNumber' | 'secondNumber' | 'thirdNumber' | 'fourthNumber', number>

```

2022-06-19 16:24 UTC, moonheekim0118 commented on src/types/card.interface.ts
> +}
간지나서 제안함22
ㅋㅋㅋㅋ근데 Record 로 객체 정의하면 더 확실하게 타입핑한다고..어디서 주워듣긴 했습니다..
아마도 객체의 key 값 타입도 정의할 수 있어서 아닐까하는 추측
```suggestion
type expireDate = Record<'month' | 'year' , string>
```

2022-06-19 16:24 UTC, moonheekim0118 commented on src/components/common/InputBox.tsx
> +
모든 Property 가 다 optional 이군요..!
만약 정말로 진짜로 최종으로 Props에 required 가 추가되지 않는다는게 보장된다면 
Partial <- 이라는 간지나는 녀석을 쓸 타이밍인것 같습니다.

```suggestion
interface InputBoxComponent {
  children: React.ReactNode;
  width: string;
  color: string;
  backgroundColor: string;
  justifyContent: justifyContent;
  padding: string;
}

export const InputBox = ({
  children,
  width,
  color,
  backgroundColor,
  justifyContent,
  padding,
}: Partial<InputBoxComponent>) => {
  return (
    <InputBoxStyle
      width={width}
      color={color}
      backgroundColor={backgroundColor}
      justifyContent={justifyContent}
      padding={padding}
    >
      {children}
    </InputBoxStyle>
  );
};

```

https://www.typescriptlang.org/docs/handbook/utility-types.html

2022-06-19 16:45 UTC, moonheekim0118 commented on src/components/cardRegister/CVCInput.tsx
> +
Number.isNaN 으로 계속 타입가드를 넣어주고있는데,
이것보다는 `typeof ` 나 `instanceof ` 를 사용하는게 어떨까요?
그리고, e.target.value 를 바꾸어버리는것은 지양하는게 어떨까하는..소심한 제안~~

2022-06-19 16:45 UTC, moonheekim0118 commented on src/components/cardRegister/CardNumbersInput.tsx
> +            value={cardNumbers?.[name]}
제가 찾아본 바로는 cardNumber 타입에는 name 속성이 아예 정의되어있지 않은데, 혹시 이 부분 설명해주실 수 있으실까요..?! 👀

2022-06-19 16:45 UTC, moonheekim0118 commented on src/constants/constants.ts
> +
발견!!!!!!!!!! 이건 진짜 Record를 써야한다!!!!!!!!!!!!

```suggestion

type modalNameConstant =  Record<string, modalName >;

```

2022-06-19 16:45 UTC, moonheekim0118 commented on src/constants/color.ts
> +};
상수는~~ readonly로 만듭시다~~~ 
```suggestion
export const COLORS = {
  WHITE_50: "#FFFFFF",
  WHITE_100: "#ecebf1",
  WHITE_125: "#e5e5e5",
  WHITE_150: "#d3d3d3",
  WHITE_200: "#D2D2D2",
  GRAY_100: "#bababa",
  GRAY_200: "#9ca3af",
  GRAY_250: "#737373",
  GRAY_275: "#575757",
  GRAY_300: "#525252",
  BLACK_100: "#000000",
  YELLOW_100: "#cbba64",
  GREEN_100: "#04c09e",
  GREEN_200: "#94daca",
  RED_100: "#ff0000",
  RED_200: "#ff6d6d",
} as const;
```

2022-06-20 16:25 UTC, usageness commented on src/components/cardRegister/CardExpireDateInput.tsx
> +
헉.. parseInt에 그런 동작이 있는줄 몰랐네요...
Number을 사용하는게 여러가지 면에서 더 좋겠어요 😥 

- [refactor: parseInt를 Number로 변경](https://github.com/usageness/react-payments/pull/1/commits/fcfc46a2b855153b9aa8cb125d134a450bb8a19a)

2022-06-20 16:31 UTC, usageness commented on src/components/cardRegister/CardNumbersInput.tsx
> +
의도하지 않은 any 였습니다...!
익숙하지 않다보니 놓치고 말았네요 😥

- [chore: useRef 타입 추가](https://github.com/usageness/react-payments/pull/1/commits/3f006eab3a0de74ea8ed6764b13f9096fd06f274)

2022-06-20 16:31 UTC, usageness commented on src/constants/constants.ts
> +};
안전한 프로그래밍 습관! 좋아요!
밑에 같은 내용의 리뷰가 있어서 커밋은 그 쪽에 남길게요 😊

2022-06-20 16:31 UTC, usageness commented on src/pages/CardRegisterPage.tsx
> +  });
initial value 를 기반으로 타입 추론을 해주더라구요! 요 귀여운 녀석... 😊😊

2022-06-20 16:31 UTC, usageness commented on src/utils/currentDate.js
> +};
아차차... 자스친구가 유틸에 숨어있었네~~
다음부터는 ts 말 잘 들어야한다~?

- [chore: currentDate 파일 ts 변환](https://github.com/usageness/react-payments/pull/1/commits/b445d9f97667bc389f9351e68f6bf0035cae0c6a)

2022-06-20 16:32 UTC, usageness commented on src/types/card.interface.ts
> +}
오... 레코드.. 처음봅니다... 👍👍

추가로 찾아보니 Record가 나오기 전까지는 저런 방식으로 했었다고 하네 😎
index signature 이라고 치니까 나옵니다!

2022-06-20 16:32 UTC, usageness commented on src/constants/constants.ts
> +
인정!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

묘하게 다른 언어의 tuple 자료형이 생각나는 Record...!

2022-06-20 16:32 UTC, usageness commented on src/constants/color.ts
> +};
아차차....22 read only 좋아요!!

- [refactor: 상수에 readonly 추가](https://github.com/usageness/react-payments/pull/1/commits/0d59a0ce840662ffa96110d8eeb0245a3a445fe3)

2022-06-20 16:32 UTC, usageness commented
**호프~~** 자세한 리뷰 정말 고맙습니다 🙌🙌

코멘트로 짚어주셨던 부분들 모두 적용했고, 찾아보면서 많은 공부가 되었어요!
어쩐지 저만 공부한 것 같아 한 편으론 조금 미안하지만... 호프도 리뷰를 하면서 많이 성장했길 바라요 😊
타스 고수 호프의 PR... 점점 더 기대됩니다 👀

: DRAFT :

### 공통 리뷰 반영 목록
- [refactor: type/interface type 포스트픽스 제거](https://github.com/usageness/react-payments/pull/1/commits/3534b9562deac1dacfa254dd794aa2398a25ddfc)
- [refactor: interface/type 이름을 소문자로 시작하도록 수정](https://github.com/usageness/react-payments/pull/1/commits/776b14bbfbe6173e5c9e521a96b6498225a31e18)
- [refactor: PropsWithChildren 적용](https://github.com/usageness/react-payments/pull/1/commits/0c0d103494cfb6f18aaf23e3fa938cfcec8e7eb6)

2022-06-24 08:57 UTC, usageness commented on src/components/common/InputBasic.tsx
> +  maxLength?: string | number;
네이티브 속성은 상속을 이용하자! 메모...
덧붙이자면 pattern과 width(🤔너는 왜..?) 도 네이티브라서 생략 가능하네요!

- [refactor: inputBasic 인터페이스 중 네이티브 타입을 상속으로 변경](https://github.com/usageness/react-payments/pull/1/commits/d73d073c797353f45614425e72f5a7b21be31266)

2022-06-24 09:00 UTC, usageness commented on src/components/common/InputUnderline.tsx
> +}
맞습니다! 😊

- [refactor: inputUnderline 인터페이스 중 네이티브 타입을 상속으로 변경](https://github.com/usageness/react-payments/pull/1/commits/ac6ac20826361e6bf8195b782fda4b174b15420b)

2022-06-24 09:11 UTC, usageness commented on src/components/common/Button.tsx
> +  textAlign?: textAlign;
간단하게 할 수 있었는데 괜히 다중 상속 찾고 있었네요..ㅋㅋㅋㅋ

- [refactor: Button 인터페이스 중 네이티브 타입을 상속으로 변경](https://github.com/usageness/react-payments/pull/1/commits/46a7ed441773a9e8a886d6dcc59221a184321ab1)

2022-06-24 09:58 UTC, usageness commented on src/components/cardRegister/CardExpireDateInput.tsx
> +    }
`Number`를 앞에 붙여주다 보니 형변환이 먼저 일어날거라고 생각했었나봐요... 멍청했습니다

타입가드와 validation을 나눠주는 아이디어도 좋은 것 같아요!

처음엔 input type을 number로 받아 형변환 자체를 없애주는 방법도 생각했었는데
type을 text로 두고, pattern을 통해 검사하는게 사용성 측면에서 더 좋게 느껴져서 포기했었던 기억이나네요.
결론은 계속 고민하다가... 안 고치고 넘어간 것 같습니다..^^ 😅

- [refactor: 타입가드와 validation을 분리](https://github.com/usageness/react-payments/pull/1/commits/5b7f46606420e0485dac8014c3cb6ce8ef02a971)

2022-06-24 10:03 UTC, usageness commented on src/components/common/PageTitle.tsx
> +  onClick?: () => void;
PageTitleComponent 의 onClick은 이런식으로 함수를 직접 넘겨서 사용하여 이벤트 객체를 넣어주지 않았어요!
이런 경우에는 굳이 이벤트 객체를 넣어주지 않아도 괜찮다고 생각합니다 😊

```jsx
<PageTitle onClick={() => navigate("/cardList")} visible={true}>
```

2022-06-24 16:55 UTC, usageness commented on src/pages/CardRegisterPage.tsx
> +  };
return type을 정의해주는 김에, `modalContents` 타입을 만들어서 Modal들에게 적용해주었어요!
이렇게 해주니까 리턴 타입과 함수들의 역할이 좀 더 명확해보이네요 😊

```ts
const loadModal: () => modalContents = () => {
```

- [refactor: modalComponent의 return type 정의 및 적용](https://github.com/usageness/react-payments/pull/1/commits/71fe78f5d08ad69be764126e5315f6045e5fd350)

2022-06-24 17:57 UTC, usageness commented on src/types/card.interface.ts
> +  cardCVC: string;
맞습니다... 카드가 추가될때 이전 인덱스 값에 하나씩 더하면서 받다보니
number 타입을 같이 넣게 되었네요 😅😅 
string 값으로 통일해주었어요!

- [refactor: id 값을 string 타입으로 통일](https://github.com/usageness/react-payments/pull/1/commits/0e6a099831946ea55f8d10b28cc4f6e6b2d29b60)

2022-06-25 08:29 UTC, usageness commented on src/types/css.type.ts
> +};
링크의 csstype 라이브러리에서 웬만한 타입들은 다 제공해주고 있네요!
감동이에요... `css.type.ts` 를 완전히 걷어냈습니다!

- [refactor: 커스텀 css 타이핑을 csstype으로 변경](https://github.com/usageness/react-payments/pull/1/commits/1632b7979e6f1e1d0d357e0c4f87105394fd74b3)

2022-06-25 08:31 UTC, usageness commented on src/types/card.interface.ts
> +}
좀 더 모던한 방법인 Record를 애용합시다! 🐱

- [refactor: 객체 프로퍼티 타입을 Record로 지정하도록 변경](https://github.com/usageness/react-payments/pull/1/commits/282874eb99cff72799dda7def01994478a45fcbd)

2022-06-25 17:02 UTC, usageness commented on src/components/common/InputBox.tsx
> +
모든 optional interface를 가진 컴포넌트에 Partial을 적용해주었어요!
물음표가 사라지니까 속이 다 시원합니다 😎😎😎

- [refactor: optional interface에 Partial 적용](https://github.com/usageness/react-payments/pull/1/commits/8b27d01a4e14f44213630d6918b5ea1fad2f9aa4)

2022-06-25 17:09 UTC, usageness commented on src/components/cardRegister/CardNumbersInput.tsx
> +            value={cardNumbers?.[name]}
![image](https://user-images.githubusercontent.com/28296575/175783714-66a48cd3-06df-4009-9b71-902fb6452969.png)

name 속성 같은 경우는 컴포넌트 위쪽에 정의된 `DEFAULT_CARD_NUMBERS_TYPE` 객체에서 받아오고 있어요!

```ts
const DEFAULT_CARD_NUMBERS_TYPE: Array<cardNumberInputObject> = [
  { name: "firstNumber", type: "text" },
  { name: "secondNumber", type: "text" },
  { name: "thirdNumber", type: "password" },
  { name: "fourthNumber", type: "password" },
];
```

해당 객체에서 cardNumberInputObject > name 부분이 cardNumberInputName 타입으로 정의되어 있답니다!

2022-06-25 19:17 UTC, usageness commented on src/components/cardRegister/CVCInput.tsx
> +
앗.. 이건 기능상의 문제가 있었던 코드였네요 😥
처음 의도는 타입가드가 아닌 `12s` 와 같은 문자열 값이 들어오는걸 방지하고,
이를 지워주는 동작을 진행하도록 했는데 제대로 동작하지 않고 있었어요.
그래서 1차적으로 아래처럼 수정하였어요.

```ts
if (Number.isNaN(Number(value))) {
  e.target.value = value.slice(0, value.length - 1);
  return;
}
```

이렇게 놓고 보니 `typeof` 나 `instanceof` 키워드로 타입 가드를 적용할 수 있을 것 같지가 않더라구요.
아쉽게도 NaN의 타입은 number이기 때문에... '하나 이상의 문자열이 섞인 입력 값' 을 찾아내기엔 어려웠어요.

(NaN을 따로 타입으로 지정해서 글로벌에 올린다면...? 가능할지도)

대신 알려주신 키워드를 이용해서 다른 타입 가드들에 적용할 수 있도록 해볼게요!

- [fix: CVCInput 입력값 검증 오류 수정](https://github.com/usageness/react-payments/pull/1/commits/127b18d002cd82efd4122a4a3694a49daa960417)

---

두 번째로 `e.target.value`를 직접적으로 바꾸는건 지양하자는 의견에는 매우매우 공감합니다!
이미 제어 컴포넌트로 사용하고 있는데 e.target.value를 건드리는건
안전하지도, 일관적이지도 않은 접근 방식이라는 생각이 드네요.

일반적인 피드백이었다면 바로 적용했겠지만...!!
이번 단계는 TS 적응을 위한 단계니까 구조 변경은 넘어가...도록 하겠습니다 😭😭 
좋은 의견 정말 감사합니다 🙏

2022-06-30 12:19 UTC, moonheekim0118 commented on src/components/common/InputBasic.tsx
> +  maxLength?: string | number;
와 패턴!! 꿀팁 알아갑니다 줍줍

2022-06-30 12:19 UTC, moonheekim0118 commented on src/components/common/InputUnderline.tsx
> +}
맞아서 뭐 어쨌다는거죠?? 성의있게 리뷰 반영을 해주세요.

2022-06-30 12:19 UTC, moonheekim0118 commented on src/components/common/InputUnderline.tsx
> +}
맞고싶으세요?

2022-06-30 12:20 UTC, moonheekim0118 commented on src/components/cardRegister/CardExpireDateInput.tsx
> +    }
셀프회고 좋습니다. 좋은 리뷰이의 자세네요. 합격입니다.

2022-06-30 12:20 UTC, usageness commented on src/components/common/InputUnderline.tsx
> +}
네~

2022-06-30 12:20 UTC, moonheekim0118 commented on src/components/common/PageTitle.tsx
> +  onClick?: () => void;
WoW

2022-06-30 12:21 UTC, moonheekim0118 commented on src/pages/CardRegisterPage.tsx
> +  };
WoW

2022-06-30 12:22 UTC, moonheekim0118 commented on src/types/card.interface.ts
> +  cardCVC: string;
말 잘들으시네요

2022-06-30 12:22 UTC, moonheekim0118 commented on src/types/css.type.ts
> +};
와우..... 👍

2022-06-30 12:23 UTC, moonheekim0118 commented on src/types/card.interface.ts
> +}
👏 👏 👏

2022-06-30 12:23 UTC, moonheekim0118 commented on src/components/common/InputBox.tsx
> +
아주 속이 시원하시죠?

2022-06-30 12:23 UTC, moonheekim0118 commented on src/components/cardRegister/CVCInput.tsx
> +
WoW..!

2022-06-30 12:24 UTC, moonheekim0118 commented on src/components/cardRegister/CardNumbersInput.tsx
> +            value={cardNumbers?.[name]}
ㅇㅎ 제가 놓쳤네요 ㅈㅅ

2022-06-30 12:24 UTC, moonheekim0118 commented on src/constants/constants.ts
> +
tuple..그런 무서운 말 하지마세요.

2022-06-30 12:26 UTC, moonheekim0118 approved these changes
안녕하세요 유세지. 리뷰어로 온 호프입니다~
늦게 리뷰해서 정말 죄송합니다 ㅠㅠ 사죄의 의미로 리뷰어와의 식사권 드립니다. 언제든 써주세요^^
리뷰 반영을 너무 착실히 해주셔서 감사하네요...저도 많이 찾아보면서 했답니다.ㅎㅎ
저도 많이 배울 수 있었던 스터디 같아요.
세지 스터디 드디어 끝내신거 축하드립니다. 방학때 하기 싫으셨을텐데 고생하셨네요.
다음 방학때는 면접 스터디로 돌아옵시다^^ 약속~~
그럼 레벨3 화이팅하시고 모모 기대할게요..빨리 만들어주세요 첫 사용자이자 성공한 유저가 되고싶어요. ^^

2022-06-30 12:27 UTC, merged